import { MemoryRememberTool, MemoryRecallTool, MemoryForgetTool } from "../memory/tools"
import { MeshSendTool, MeshPeersTool, MeshDelegateTool } from "../mesh/tools"
import {
  GmailSearchTool,
  GmailReadTool,
  GmailCountTool,
  GmailDraftTool,
  GmailReplyTool,
  GmailArchiveTool,
  CalendarReadTool,
  CalendarWriteTool,
  CalendarUpdateTool,
  CalendarDeleteTool,
  DriveSearchTool,
  DriveReadTool,
  DriveListTool,
  ContactsSearchTool,
  ContactsGetTool,
  ContactsCreateTool,
  ContactsUpdateTool,
  SheetsReadTool,
  SheetsWriteTool,
  SheetsAppendTool,
  SheetsListTool,
  ChatSpacesTool,
  ChatReadTool,
  ChatSendTool,
} from "../google"
import { TelegramSendTool, TelegramReadTool } from "../telegram/tools"
import { CouncilTool } from "./council/tool"
import {
  TrelloBoardsTool,
  TrelloListsTool,
  TrelloCardsTool,
  TrelloReadTool,
  TrelloCreateTool,
  TrelloUpdateTool,
  TrelloCommentTool,
} from "../atlassian"

export const harnessToolEffects = [
  MemoryRememberTool,
  MemoryRecallTool,
  MemoryForgetTool,
  MeshSendTool,
  MeshPeersTool,
  MeshDelegateTool,
  GmailSearchTool,
  GmailReadTool,
  GmailCountTool,
  GmailDraftTool,
  GmailReplyTool,
  GmailArchiveTool,
  CalendarReadTool,
  CalendarWriteTool,
  CalendarUpdateTool,
  CalendarDeleteTool,
  DriveSearchTool,
  DriveReadTool,
  DriveListTool,
  ContactsSearchTool,
  ContactsGetTool,
  ContactsCreateTool,
  ContactsUpdateTool,
  SheetsReadTool,
  SheetsWriteTool,
  SheetsAppendTool,
  SheetsListTool,
  ChatSpacesTool,
  ChatReadTool,
  ChatSendTool,
  TrelloBoardsTool,
  TrelloListsTool,
  TrelloCardsTool,
  TrelloReadTool,
  TrelloCreateTool,
  TrelloUpdateTool,
  TrelloCommentTool,
  TelegramSendTool,
  TelegramReadTool,
  CouncilTool,
] as const
